up to date

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,28 +1,84 @@
-#!usr/bin/env bash
-#configuring web-01 to have an HTTP reponse header
+#!/usr/bin/env bash
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-#updating packages
-sudo apt-get updates
-sudo apt-get install -y nginx
+# uncomment to see the script run in action
+#set -x
 
-#creating an index page
-echo "hello world!" | sudo tee /var/www/html/index.html
+echo -e "Updating and doing some minor checks...\n"
 
-#performing a redirection
-new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/alpheus-tema permanent;"
+function install() {
+	command -v "$1" &> /dev/null
 
-sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-#creating a custom error page
+install nginx #install nginx
 
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
+echo -e "\nSetting up some minor stuff.\n"
 
-# custom HTTP reponse header
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
 
-sudo sed -i "server_name _;/a add_header x-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-#test for syntax errors
-sudo nginx -t
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-#restart nginx
-sudo service nginx restart
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
